# Agenda : Numpy

***

## Contents:
* Basics of Numpy
* Advance stuffs in Numpy
* Exerciase in Numpy


In [1]:
import numpy as np

## What is Numpy?

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object

* sophisticated (broadcasting) functions

* tools for integrating C/C++ and Fortran code

* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.


In order to know all the functationalities in a package use dir(package_name). For example dir(np)
For more: https://numpy.org/devdocs/user/quickstart.html

In [2]:
a= [1,34,56,78]

In [3]:
A= np.array([1,34,56,78])

In [4]:
type(a)

list

In [11]:
# stop in not included in the array creation
B=np.arange(0,100,2)

In [12]:
np.shape(B)

(50,)

In [88]:
#ndarray.size
#the total number of elements of the array. This is equal to the product of the elements of shape.
np.size(B)

50

In [20]:
C=B.reshape(10,5)
C

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [17]:
np.shape(C)

(10, 5)

In [18]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
I=np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
B=np.arange(0,100,2)
C=B.reshape(10,5)
C


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [92]:
# linespace creates an array with target number of elements where as arrange use steps 
Z=np.linspace( 1, 100, 9).reshape(3,3)
Z

array([[  1.   ,  13.375,  25.75 ],
       [ 38.125,  50.5  ,  62.875],
       [ 75.25 ,  87.625, 100.   ]])

In [25]:
D=np.arange(0,200,4)
D=D.reshape(5,10)
D

array([[  0,   4,   8,  12,  16,  20,  24,  28,  32,  36],
       [ 40,  44,  48,  52,  56,  60,  64,  68,  72,  76],
       [ 80,  84,  88,  92,  96, 100, 104, 108, 112, 116],
       [120, 124, 128, 132, 136, 140, 144, 148, 152, 156],
       [160, 164, 168, 172, 176, 180, 184, 188, 192, 196]])

In [31]:
#Matrix multiplcation using Dot function in munply
E=np.dot(C,I)
E

array([[ 0.,  2.,  4.,  6.,  8.],
       [10., 12., 14., 16., 18.],
       [20., 22., 24., 26., 28.],
       [30., 32., 34., 36., 38.],
       [40., 42., 44., 46., 48.],
       [50., 52., 54., 56., 58.],
       [60., 62., 64., 66., 68.],
       [70., 72., 74., 76., 78.],
       [80., 82., 84., 86., 88.],
       [90., 92., 94., 96., 98.]])

In [93]:
C@I

array([[ 0.,  2.,  4.,  6.,  8.],
       [10., 12., 14., 16., 18.],
       [20., 22., 24., 26., 28.],
       [30., 32., 34., 36., 38.],
       [40., 42., 44., 46., 48.],
       [50., 52., 54., 56., 58.],
       [60., 62., 64., 66., 68.],
       [70., 72., 74., 76., 78.],
       [80., 82., 84., 86., 88.],
       [90., 92., 94., 96., 98.]])

In [98]:
K=np.eye(5)
E=np.dot(C,K)
K*I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# Add all the values of a matrix
sum_total= np.sum(D)
sum_total

4900

In [37]:
C

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [39]:
# Add all the value of axis(row)

np.sum(C,axis=1)

array([ 20,  70, 120, 170, 220, 270, 320, 370, 420, 470])

In [40]:
# add all the even numbers between 0 to 100
np.sum(C)

2450

In [42]:
# Add all the value of axis(column)
np.sum(C,axis=0)

array([450, 470, 490, 510, 530])

In [43]:
np.random.rand(5,6)

array([[0.83793881, 0.55668439, 0.56112397, 0.73989076, 0.39265901,
        0.66663988],
       [0.6192441 , 0.41379729, 0.04076816, 0.8709482 , 0.16310262,
        0.48134514],
       [0.73850644, 0.79972458, 0.91772921, 0.37744114, 0.96709165,
        0.62002717],
       [0.23150648, 0.62976331, 0.1636665 , 0.75817391, 0.89462514,
        0.03930959],
       [0.72659671, 0.00203086, 0.40126271, 0.82285578, 0.12003686,
        0.15151121]])

In [45]:
# Append a number to a list array
A=np.append(A,19)
A

array([ 1, 34, 56, 78, 19, 19])

In [47]:
# Minimum of each rows

np.min(C,axis=1)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
np.min(C)

0

In [49]:
np.max(C)

98

In [50]:
# Stacking in a array
x=[1,2,3]
y=[5,6,7]
z=[3,5,7]

In [59]:
# Performing a vertical stack using list
V=np.vstack((x,y,z))
V

array([[1, 2, 3],
       [5, 6, 7],
       [3, 5, 7]])

In [60]:
V=np.vstack((x,z,y))
V

array([[1, 2, 3],
       [3, 5, 7],
       [5, 6, 7]])

In [61]:
# Horizontal stack
H=np.column_stack((x,y,z))
H

array([[1, 5, 3],
       [2, 6, 5],
       [3, 7, 7]])

In [62]:
# Transpose function in numpy
np.transpose(H)

array([[1, 2, 3],
       [5, 6, 7],
       [3, 5, 7]])

In [73]:
C


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [103]:
# Calculation happens from 0 and hence if you want to extract information from nth row , give input n-1
F=C[3:6,1:3]
F


array([[32, 34],
       [42, 44],
       [52, 54]])

In [72]:
# Calculation happens from 0 and hence if you want to extract information from nth row , give input n-1
F=C[:3]
F

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [101]:
F=C[3:-1]
F

array([[30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88]])

In [80]:
F=C[2:3]
F

array([[20, 22, 24, 26, 28]])

In [84]:
F=C[2:3]
F

array([[20, 22, 24, 26, 28]])

In [85]:
# Operation on a array
X=F+1
X

array([[21, 23, 25, 27, 29]])

In [86]:
F+[1,2,3,4,5]

array([[21, 24, 27, 30, 33]])

In [87]:
F*7

array([[140, 154, 168, 182, 196]])

## Broadcasting

## Some more examples of Numpy methods/functions

For several methods, an optional out argument can also be provided and the result will be placed into the output array given. The out argument must be an ndarray and have the same number of elements. It can have a different data type in which case casting will be performed.

    ndarray.argmax([axis, out])    Return indices of the maximum values along the given axis.
    ndarray.min([axis, out, keepdims])    Return the minimum along a given axis.
    ndarray.argmin([axis, out])    Return indices of the minimum values along the given axis of a.
    ndarray.ptp([axis, out])    Peak to peak (maximum - minimum) value along a given axis.
    ndarray.clip([min, max, out])    Return an array whose values are limited to [min, max].
    ndarray.conj()    Complex-conjugate all elements.
    ndarray.round([decimals, out])    Return a with each element rounded to the given number of decimals.
    ndarray.trace([offset, axis1, axis2, dtype, out])    Return the sum along diagonals of the array.
    ndarray.sum([axis, dtype, out, keepdims])    Return the sum of the array elements over the given axis.
    ndarray.cumsum([axis, dtype, out])    Return the cumulative sum of the elements along the given axis.
    ndarray.mean([axis, dtype, out, keepdims])    Returns the average of the array elements along given axis.
    ndarray.var([axis, dtype, out, ddof, keepdims])    Returns the variance of the array elements, along given axis.
    ndarray.std([axis, dtype, out, ddof, keepdims])    Returns the standard deviation of the array elements along given axis.
    ndarray.prod([axis, dtype, out, keepdims])    Return the product of the array elements over the given axis
    ndarray.cumprod([axis, dtype, out])    Return the cumulative product of the elements along the given axis.
    ndarray.all([axis, out, keepdims])    Returns True if all elements evaluate to True.
    ndarray.any([axis, out, keepdims])    Returns True if any of the elements of a evaluate to True.
    ​


# Next class will be on Pandas library